# Generated by Django 4.1.3 on 2022-11-24 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                ("fullname", models.CharField(max_length=30)),
                (
                    "date_joined",
                    models.DateTimeField(auto_now_add=True, verbose_name="date joined"),
                ),
                (
                    "last_login",
                    models.DateTimeField(auto_now=True, verbose_name="last login"),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={"abstract": False,},
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "account",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("transaction_count", models.PositiveIntegerField(default=0)),
                ("transaction_item_count", models.PositiveIntegerField(default=0)),
                ("transaction_total_count", models.BigIntegerField(default=0)),
                (
                    "membership_status",
                    models.CharField(
                        choices=[
                            ("NO", "Not a member"),
                            ("SV", "Silver"),
                            ("GD", "Gold"),
                            ("PT", "Platinum"),
                            ("DM", "Diamond"),
                        ],
                        default="NO",
                        max_length=2,
                    ),
                ),
                ("membership_points", models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Adress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("province", models.CharField(max_length=255)),
                ("regency", models.CharField(max_length=255)),
                ("district", models.CharField(max_length=255)),
                ("zipcode", models.CharField(max_length=10)),
                ("adress", models.TextField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="account.customer",
                    ),
                ),
            ],
        ),
    ]
