# Generated by Django 4.1.3 on 2022-11-24 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_rename_fullname_account_username"),
    ]

    operations = [
        migrations.RenameModel(old_name="Adress", new_name="Address",),
        migrations.RenameField(
            model_name="address", old_name="adress", new_name="address",
        ),
    ]
