# Generated by Django 4.1.3 on 2022-12-17 05:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_customer_last_view_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="last_view_products",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), default=list, size=None
            ),
        ),
    ]
