# Generated by Django 4.1.3 on 2022-11-26 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_colorandsize"),
    ]

    operations = [
        migrations.CreateModel(
            name="ColorAndSizeAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                ("available", models.BooleanField(default=False)),
                (
                    "color_and_size",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="product.colorandsize",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_cs",
                        to="product.product",
                    ),
                ),
            ],
        ),
    ]
