# Generated by Django 4.1.3 on 2022-11-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_colorandsizeavailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="prduct")),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ManyToManyField(blank=True, to="product.imageproduct"),
        ),
    ]
