# Generated by Django 4.1.3 on 2022-11-27 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_imageproduct_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageproduct",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.color",
            ),
        ),
    ]
