# Generated by Django 4.1.3 on 2022-11-27 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_imageproduct_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="lengan_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="material_desc",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="size_desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
