# Generated by Django 4.1.3 on 2022-11-27 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_product_lengan_desc_product_material_desc_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="discount",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="product", name="price", field=models.PositiveIntegerField(),
        ),
    ]
