# Generated by Django 4.1.3 on 2022-12-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_product_discount_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="stock_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
