# Generated by Django 4.1.3 on 2022-12-16 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_customer_account"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="cart", name="address",),
        migrations.RemoveField(model_name="cart", name="datetime",),
        migrations.AlterField(
            model_name="cart",
            name="customer",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="account.customer",
            ),
        ),
    ]
