# Generated by Django 4.1.3 on 2022-12-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_remove_cart_address_remove_cart_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="orders",
                to="orders.productcontainer",
            ),
        ),
    ]
