# Generated by Django 4.1.3 on 2022-12-17 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_product_sold_count_product_stock_count"),
        ("orders", "0003_alter_cart_products"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcontainer",
            name="color_and_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="product.colorandsize",
            ),
        ),
    ]
